### ISSUE TITLE
Allow custom curl settings

### ISSUE THREAD

**Issue by MarcusDalgren** [Shopello/Shopello-PHP#1]
Right now the call to $this->curl->reset(); will reset all settings on the Curl object.
This means that passing in a Curl object serves no real purpose from a consumer perspective since it will get reset before use anyway.

We currently have to use a proxy in order to send our requests through a static ip and the only way to do this is to set curl options after the reset. This works but isn't all that elegant.

We'll send a pull request hopefully some time later this week.

**Comment by etu** [comment]
The reason we had for passing the Curl object is for Dependency Injection reasons. But if you have a fix that would make this easier for you, feel free to send a pull request. I'm happy as long it doesn't break the signature or expected result of any method.

**Comment by etu** [comment]
5a8769e0f188262e82d646936c071486e3415f6f and 0d2cc897edbc73c10d0a9bcaefa9e1b578fbaa54 is live and is shipped with the new tag `1.0.6`.
