### ISSUE TITLE
Consider switching to Guzzle

### ISSUE THREAD

**Issue by MarcusDalgren** [Shopello/Shopello-PHP#2]
Right now you're using the very basic Curl package which does the basics and works fine in nix environments. However the package doesn't work in Windows and there are issues around how the config is handled and reused between requests.
I suggest switching to Guzzle for all your curl needs. It's a very robust library with much better error/exception handling. You're currently requiring PHP version 5.4 via the curl package and the latest Guzzle version for 5.4 is 5.3.
We would be willing to create a pull request for this if you like the idea. This should solve the config reuse issues as Guzzle is built around reusing the same client for sending multiple requests.

**Comment by etu** [comment]
Correct me if I'm wrong. But from what I've read, I've learned that Guzzle tend to break their API very often.

But we have looked into this library instead: http://phphttpclient.com/ which seems to be very plain and simple to use. It also supports >=5.3.

**Comment by MarcusDalgren** [comment]
They used to have a pretty rapid development pace but the only time I've had problems is when switching between major versions. In your case you'd most likely lock down on version any way.
For example you've locked the curl library to 1.2.0. This might not be ideal with a library as popular as Guzzle since there could be conflicts with other libraries.
From that point of view a less popular library might be easier.
Our main pain points right now are that we can't really configure the underlying client when sending requests and any decent solution where a client is handed in and then reused with the initial settings intact is a good solution for us.

**Comment by etu** [comment]
With that in mind, I think I'll close this. We might avoid unnecessary conflicts by not running Guzzle.
